### ISSUE TITLE
add upper plotly.py version constraint

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly_express#102]
We should do another release of `plotly_express` that specifies an upper version constraint of plotly `<4.0.0a0`.  Because we're integrating `plotly_express` into plotly.py v4, it would be good to avoid having folks install both `plotly_express` and `plotly>=4.0.0`.

**Comment by nicolaskruchten** [comment]
yep, PR it in and I'll do the release ;)

**Comment by nicolaskruchten** [comment]
Actually, I thought the "final" version of `plotly_express` would just re-export all of `plotly.express` instead... ?

**Comment by jonmmease** [comment]
PR in https://github.com/plotly/plotly_express/pull/103.

> Actually, I thought the "final" version of plotly_express would just re-export all of plotly.express instead... ?

I think we should do both.  Release the constrained version now, then when plotly.py v4 comes out, release a skeleton `plotly_express` that only remaps `plotly.express`.
