### ISSUE TITLE
Faceting by row yaxis matched range

### ISSUE THREAD

**Issue by WillKoehrsen** [plotly/plotly_express#105]
Currently, when faceting by row on a scatter plot, the yaxis for both graphs is set to the same range. This results in uninformative graphs when there is a major difference in the range across two distributions. For example, in the below graph:

```
fig = px.scatter(
    grouped,
    x="n_estimators",
    y="mean_ape",
    facet_row="measurement_type",
    color="bootstrap",
    title="Error vs Number of Estimators Colored by Bootstrap",
    height=1000, width=1600
)
```

<img width="1430" alt="Screen Shot 2019-06-17 at 09 10 57 EDT" src="https://user-images.githubusercontent.com/17484616/59606739-e6745080-90df-11e9-8c02-432f87803b71.png">

One way around this is to modify the layout so the second yaxis does not match the first.

```
# Initial
fig.layout['yaxis2']

layout.YAxis({
    'matches': 'y', 'title': {'text': 'mean_ape'}
})


# Alter so the second yaxis does not match the first
fig.layout['yaxis2'] = dict(title=dict(text='mean_ape'))
```

The graph is now a little easier to understand:

<img width="1454" alt="Screen Shot 2019-06-17 at 09 12 49 EDT" src="https://user-images.githubusercontent.com/17484616/59606881-34895400-90e0-11e9-9dc7-5e4a4948b5a0.png">

Is there a way to add a parameter to `px.scatter` (or other graphs) so the user can choose if the axes are matched when faceting?

**Comment by nicolaskruchten** [comment]
I'll think about whether it makes sense to do this as an additional kwarg, but it should be doable by appending something like `.udpate_yaxes(matches=None)` to any PX call.

**Comment by WillKoehrsen** [comment]
Ah, thanks for the suggestion!
