### ISSUE TITLE
Vertical X axis labels

### ISSUE THREAD

**Issue by ingeneious** [plotly/plotly_express#106]
I have rather long strings as the labels for each X value, and they are currently tilted and getting cut off. Is there any way to have them vertical and show the full string?

**Comment by nicolaskruchten** [comment]
Plotly Express sets the `automargin` flag in the underlying Javascript library which tries to leave room for labels but if they would take up more than 50% of the side of the figure it gives up... If you labels are really extremely long you could try increasing the size of your figure?
