### ISSUE TITLE
how could i use ploty_express with the data like this

### ISSUE THREAD

**Issue by zha0yangchen** [plotly/plotly_express#107]
![O1YWLM4CR$T1``@L9F7_MGB](https://user-images.githubusercontent.com/30195534/60157349-1f6b9e00-9821-11e9-8c7c-2e24be1e103e.png)
my data is like this , no colum name, how could use ploty_express plot quickly? thanks!

**Comment by nicolaskruchten** [comment]
At the moment you'll have to assign a name to your columns to use Plotly Express.

**Comment by nicolaskruchten** [comment]
This is now fixed! you can reference it with 0.
