### ISSUE TITLE
Line plot function wrapping around

### ISSUE THREAD

**Issue by ingeneious** [plotly/plotly_express#109]
I have many lines that share an X axis to plot on top of each other. However, the plotly line function connects the end of one of these lines to the next with another line segment. How do I get it to realize that these are separate lines to plot?

**Comment by nicolaskruchten** [comment]
You can use the `line_group` kwarg to use a column to identify which rows belong to the same line.

**Comment by ingeneious** [comment]
I tried this by adding an extra column containing linegroups, but then the colors now are off. I am using the same color column ("cluster") as before (I am coloring K-means cluster output by color) and now when I hover over the plot, things in the same cluster are different colors. The color was working before the addition of line_group and line group did not change the dataframe other than adding a column. What could be going on?

**Comment by ingeneious** [comment]
Sorry, looks like I had a bug in assigning the line widths, which was somehow affecting the colors. I fixed it according to the other issue I posted and the colors are looking fine. Thank you so much for your help!
