### ISSUE TITLE
plotly_express installs via pip but doesnot import

### ISSUE THREAD

**Issue by nitin0301** [plotly/plotly_express#11]
Hi,

I am using Python 3.6.8 in anaconda environment.

pip install plotly_express works.:

(py3) bash-3.2$ pip install plotly_express
Requirement already satisfied: plotly_express in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (0.1)
Requirement already satisfied: plotly>=3.6.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from plotly_express) (3.7.1)
Requirement already satisfied: scipy>=0.14 in ./Library/Python/3.6/lib/python/site-packages (from plotly_express) (1.1.0)
Requirement already satisfied: pandas>=0.20.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from plotly_express) (0.21.0)
Requirement already satisfied: statsmodels>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from plotly_express) (0.9.0)
Requirement already satisfied: retrying>=1.3.3 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from plotly>=3.6.0->plotly_express) (1.3.3)
Requirement already satisfied: pytz in ./Library/Python/3.6/lib/python/site-packages (from plotly>=3.6.0->plotly_express) (2018.5)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from plotly>=3.6.0->plotly_express) (1.11.0)
Requirement already satisfied: nbformat>=4.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from plotly>=3.6.0->plotly_express) (4.4.0)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from plotly>=3.6.0->plotly_express) (2.21.0)
Requirement already satisfied: decorator>=4.0.6 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from plotly>=3.6.0->plotly_express) (4.4.0)
Requirement already satisfied: numpy>=1.8.2 in ./Library/Python/3.6/lib/python/site-packages (from scipy>=0.14->plotly_express) (1.15.0)
Requirement already satisfied: python-dateutil>=2 in ./Library/Python/3.6/lib/python/site-packages (from pandas>=0.20.0->plotly_express) (2.7.3)
Requirement already satisfied: patsy in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from statsmodels>=0.9.0->plotly_express) (0.5.1)
Requirement already satisfied: traitlets>=4.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from nbformat>=4.2->plotly>=3.6.0->plotly_express) (4.3.2)
Requirement already satisfied: jupyter-core in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from nbformat>=4.2->plotly>=3.6.0->plotly_express) (4.4.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from nbformat>=4.2->plotly>=3.6.0->plotly_express) (3.0.1)
Requirement already satisfied: ipython-genutils in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from nbformat>=4.2->plotly>=3.6.0->plotly_express) (0.2.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->plotly>=3.6.0->plotly_express) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->plotly>=3.6.0->plotly_express) (2018.8.13)
Requirement already satisfied: idna<2.9,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->plotly>=3.6.0->plotly_express) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->plotly>=3.6.0->plotly_express) (3.0.4)
Requirement already satisfied: setuptools in ./Library/Python/3.6/lib/python/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly>=3.6.0->plotly_express) (40.0.0)
Requirement already satisfied: attrs>=17.4.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly>=3.6.0->plotly_express) (19.1.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly>=3.6.0->plotly_express) (0.14.11)

BUT I cannot find the module when I do "import plotly_express":
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-ce2f5227fa18> in <module>
----> 1 import plotly_express

ModuleNotFoundError: No module named 'plotly_express'

​

**Comment by nicolaskruchten** [comment]
That's quite strange... Can you tell me a bit about your environment? Which version of Python and `pip` are you on?

**Comment by nitin0301** [comment]
Python 3.6.8  & pip 19.0.3

**Comment by nicolaskruchten** [comment]
Thanks, and sorry I missed the Python version you'd already provided at the top there... I'm not sure if it will fix your issue but I've just pushed up version `0.1.1` of `plotly_express` which requires `plotly>=3.7.1` only (and not alongside `plotly>=3.6.0`). Perhaps installing will work in your environment now?

**Comment by nitin0301** [comment]
Thanks nicolaskruchten.  It is working on my pycharm but not in conda. So, this will work for now.

**Comment by CloudChaoszero** [comment]
Hey, hope you are doing well @nitin0301. 

# Similar Scenario
I had the same issue as you. I went through to try to resolve it, but I actually found a quick workaround for this issue, while a somewhat larger issue is at hand for particular **pip** paths for some people.

# Workaround

Run this line in a cell within your Jupyter Notebook: 

```
!pip install plotly_express
```

# Root Cause

When we ran `pip install plotly_express` in our CLIs, we downloaded the package in the **system's pip** tool, and not within **anaconda's pip**. Even with the consideration of creating an environment, you would get this issue. 

After some trial and errors from finding out that upgrading[ jupyter, system's python](https://github.com/jupyter/notebook/issues/2786), and manually trying to change [the .bash_profile's filepath](https://stackoverflow.com/questions/35313876/after-installing-with-pip-jupyter-command-not-found), I got nothing. 

![Why Though](https://media.tenor.com/images/d02f68f2b8785baa2e72115dec9bceed/tenor.gif)

# Solution

After checking the diff's of the system and jupyter`pip list` and `conda list`, I thought:
"why don't I just run the command within the Jupyter Notebook?"

Ran the following, and it seems to work now.

```
#Example code from documentation
iris = px.data.iris()
px.scatter(iris, x="sepal_width", y="sepal_length")
#Enjoy the visualization, hopefully :D 
```

# Work still needed

Direct the pip and python path's from system/CLI to anaconda's paths.

Hope that helps!

**Comment by khalido** [comment]
> I am using Python 3.6.8 in anaconda environment.

when you make a new conda env, install pip in it first, otherwise when you pip install something inside the conda env it uses the base anaconda pip file.

Its quite confusing, anaconda should just install pip by default inside environments.

**Comment by matanster** [comment]
Same error with conda 4.7.12

**Comment by M-Younus** [comment]
simply upgrade the plotply

**Comment by entzyeung** [comment]
!pip install plotly_express

will fix this problem

**Comment by yesikapsari** [comment]
> !pip install plotly_express

thank you

**Comment by mqsaud** [comment]
!pip install plotly_express did not fix for vs code

**Comment by SomKamoji** [comment]
same like mqsaud it did not fix for me

**Comment by Wrench-wench** [comment]
> !pip install plotly_express did not fix for vs code

I had the same issue in VS Code on Windows 10, what fixed it for me was I was using Python3.9 installed from the Windows Store. Switching to Python installed by the Python installer solved the import issues.
