### ISSUE TITLE
Continuous color scale defunct after 0.3.0

### ISSUE THREAD

**Issue by kristomi** [plotly/plotly_express#110]
In the upgrade from 0.2.2 to 0.3.0 the ability to supply a custom continuous color scale was lost. The following works as expected, and as demoed on medium (https://medium.com/@plotlygraphs/introducing-plotly-express-808df010143d), in 0.2.2, but not in 0.3.0 and 0.3.1.:
```
import plotly_express as px
print(f"Plotly express version is {px.__version__}")
gapminder = px.data.gapminder()
px.choropleth(gapminder.query("year == 2007"),
              locations='iso_alpha',
              color='lifeExp',
              projection='natural earth',
              color_continuous_scale=px.colors.sequential.Plasma
             )
```

**Comment by nicolaskruchten** [comment]
This is working fine on my end, and in the docs (check the version number at the bottom of the page here https://www.plotly.express/ )

Can you confirm which version of `plotly` you're running with `print(plotly.__version__)` ?

**Comment by kristomi** [comment]
Thanks for getting back to me so soon! I have plotly version 3.10.0.
