### ISSUE TITLE
 404 GET /static/plotly.js?v=

### ISSUE THREAD

**Issue by John-Yao** [plotly/plotly_express#112]
I use jupyter + plotly_express by remote machine.
Sometimes( refresh the page ) the plotly  display nothing. I cannot reproduce the situation always. I notice the log as follow:
[W 15:15:22.465 NotebookApp] 404 GET /static/plotly.js?v=2019xx (xx.xx.xx.xx) 2.51ms referer=http://xx.xx.xx.xx:.ipynb
My solution now is to restart the kernel. Is there any bug in plotly or plotly_express

**Comment by nicolaskruchten** [comment]
It's not clear where this issue is coming from or how to fix it unfortunately. I've seen it crop up occasionally.

**Comment by nicolaskruchten** [comment]
Any help you could provide in replicating it would be much appreciated :)

**Comment by John-Yao** [comment]
I am sorry I cannot replicate it.

**Comment by iDmple** [comment]
Hi,

I have the same error right now, after some time of inactivity, when I returned the plots don't display anymore and I get

> 404 GET /static/plotly.js?v=

in the log.

**Comment by limdequan** [comment]
Hi!

I seem to have the same issue. In my case, the error tend to pop out when I use a function which plots a graph within a widgets.interactive_output() function.

Example:
    import plotly.graph_objects as go
    import numpy as np
    import ipywidgets as widgets
    
    def plotgraph(a):
        x = np.arange(10)
    
        fig = go.Figure(data=go.Scatter(x=x, y=x**a))
        fig.show()
     
    a = widgets.BoundedIntText(
        value=2,
        min=1,
        max=10,
        step=1,
        description='$a$'
        )

    out = widgets.interactive_output(plotgraph, {'a' : a})
    display(out)
    a.value=1

I am using:
Jupyter-notebook: 6.0.1
Python: 3.7
Plotly: 4.5.4

**Comment by nicolaskruchten** [comment]
Our Troubleshooting guide here https://plotly.com/python/troubleshooting/ is the best place to get help figuring out this kind of thing.
