### ISSUE TITLE
Plotly express histogram not showing up anymore in Jupyter notebook

### ISSUE THREAD

**Issue by saulcruzr** [plotly/plotly_express#114]
It was working good, as soon as I refreshed  it stopped showing up, have anyone here experienced that?

![plotly_express_not_working](https://user-images.githubusercontent.com/3718514/60776700-0c4bae80-a0fc-11e9-9037-d1689432a88d.png)

**Comment by nicolaskruchten** [comment]
Which version of the notebook environment are you using?

**Comment by saulcruzr** [comment]
hey nicolas,

The version of the notebook server is: 5.7.8

**Comment by nicolaskruchten** [comment]
This is pretty strange. If you restart-and-clear-output are you able to get something to render again?

**Comment by saulcruzr** [comment]
Nicolas,

That totally fixed it, it is kind of weird though. Thanks a lot.

![working_now](https://user-images.githubusercontent.com/3718514/60779893-5c317200-a10a-11e9-9015-a37774bd5917.png)

**Comment by saulcruz** [comment]
However, this stops working after an hour or so =( and have to restart the kernel every time.

**Comment by nicolaskruchten** [comment]
If you're able to reliably reproduce this I'd love to fix it. I've seen this on occasion but haven't been able to isolate it.

**Comment by toshafraley1** [comment]
I am experiencing this as well, but restarting the kernel isn't correcting the problem.

**Comment by nicolaskruchten** [comment]
@toshafraley1 unfortunately with Jupyter Notebook, usually just restarting the kernel is not enough, you need to "restart & clear output", and/or as per our Troubleshooting Guide at https://plot.ly/python/troubleshooting/, you can try running `import plotly.io as pio; pio.renderers.default='notebook'`

**Comment by toshafraley1** [comment]
Thanks @nicolaskruchten. Unfortunately, "restart & clear output" did not work either. I shutdown the notebook from the command line and started it back up via the command line. This worked. I did not try your other recommendations. I should mention that I am using Jupyter Lab.

**Comment by muneebable** [comment]
I am having the same problem. I can't able to see the output when I run the jupyter notebook from the command line. It shows nothing

**Comment by nicolaskruchten** [comment]
Please do try the steps outlined in https://plot.ly/python/troubleshooting/ that match your specific situation: Classic Notebook and Lab have different recommendations :)

I'm going to close and lock this issue now, and request that people having display problems [please open **new issues in the Plotly.py repo**](https://github.com/plotly/plotly.py/issues/new) so that we can figure them out one at a time, as it gets very confusing when people say "me too" but have slightly different setups requiring different solutions.
