### ISSUE TITLE
Format `hover_data`. Is this possible?

### ISSUE THREAD

**Issue by indiana-nikel** [plotly/plotly_express#115]
Hello,

I couldn't seem to find this in the docs. Is it possible to format `hover_data` as a string for display purposes only? My use case comes from displaying dollar amounts, but the original data is `float.64` so hovering over a data point does not look appealing. 

My current fix requires an extra column to be added to a data frame, then that column is passed to the `hover_data` argument:
```
df['hover_text'] = df['revenue'].apply(lambda x :'${0:,.0f}'.format(x))
```
 However, this is not a great solution. My knowledge is pretty limited with `plotly` so there may be better solutions I haven't been able to find currently. Perhaps with `hovertemplate`?

Best,
Indiana

**Comment by nicolaskruchten** [comment]
Your solution is probably what I would go with, to be honest. The way `hover_data` is injected into the figure is via `hovertemplate`, and you can override `hovertemplate` with `.update_trace(hovertemplate="whatever")` if you like, but it's likely to be a bit finicky.

**Comment by indiana-nikel** [comment]
Okay thank you for your quick response! Are there plans to expose this when creating a plot? 

Eg.
```
px.bar(
   df, 
   x="Revenue", 
   y="Year",
   hover_data={
      "Revenue": "${0:,.0f}", 
      ...
   })
```
Sidenote: Since discovering this plotting library, it's hard to go back to anything else!

**Comment by nicolaskruchten** [comment]
I'm glad you like it! The API you suggest above is pretty interesting, I'll think about it. The formatting strings would have to be D3.js-compatible rather than Python-compatible as the formatting happens in Javascript but other than that this seems like a nice extension.

**Comment by nicolaskruchten** [comment]
Will be completed in https://github.com/plotly/plotly.py/issues/1774
