### ISSUE TITLE
support customdata

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly_express#116]
across all chart types for easier use with dash.

**Comment by nicolaskruchten** [comment]
`hover_data` stores data in `customdata` which is both a good and bad thing. The good thing is that it's already supported (yay!) but the bad thing is that it shows up in hovers unless you do extra work to prevent it (booh!)

**Comment by nicolaskruchten** [comment]
One way to implement this would be a bit odd but would be to accept another kwarg `custom_data` which would get inserted into `trace.customdata` ahead of `hover_data` so that it could be indexed starting from 0 in callbacks...

**Comment by nicolaskruchten** [comment]
Moved to https://github.com/plotly/plotly.py/issues/1751
