### ISSUE TITLE
Suppress default hover_data

### ISSUE THREAD

**Issue by alecfwilson** [plotly/plotly_express#120]
Is there any way to suppress the default hover_data when the hover_data argument is passed? For example, my plot doesn't need the x, y, and color args in the hover_data, but I can't figure out how to remove them.

**Comment by nicolaskruchten** [comment]
At the moment there's no way to do this from the arguments, but this is something I'll look into. You can modify the hoverlabel contents fairly easily by modifying the `hovertemplate` attribute of the traces.

**Comment by nicolaskruchten** [comment]
Right now the default value of `hover_data` is `None`, and it accepts an array of columns to *add* to the existing set of key-value pairs listed (which currently include every value mapped to some visual attribute in the chart). In terms of API, I could imagine either adding a new kwarg `hover_data_exclusion` or having `hover_data` accept a dict which would control if/how values are displayed. Someone recently suggested the idea of this kind of API to control the precision/formatting of numbers in hover labels with e.g. `hover_data={"column": "format"}` and this would fit in pretty nicely as `hover_data={"column": False}`

**Comment by nicolaskruchten** [comment]
Will be completed in https://github.com/plotly/plotly.py/issues/1774

**Comment by secsilm** [comment]
> At the moment there's no way to do this from the arguments, but this is something I'll look into. You can modify the hoverlabel contents fairly easily by modifying the `hovertemplate` attribute of the traces.

For `px.choropleth_mapbox`, there is no `hovertemplate` parameter, right? I hope to do custom formatting like in `go.Choroplethmapbox`.

And I found that `px.choropleth_mapbox` has a `template` parameter, but I can't find any doc about it. Is there something I missed? Thanks.

**Comment by gpavanb-osi** [comment]
I have the same issue with `px.scatter_mapbox` as well. Currently, `lat`, `lon` and `color` are also being included in the hover text and there is no corresponding `hovertemplate`.
