### ISSUE TITLE
Cannot import name 'qualitative' from 'plotly.express.colors' 

### ISSUE THREAD

**Issue by alitarraf** [plotly/plotly_express#123]
Using plotly=4.0.0, with plotly express, there is an error when importing plotly express.
Any idea how to fix this?

```
# Standard plotly imports...
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
 in 
      2 #import plotly.plotly as py # used in older version
      3 import plotly.graph_objects as go
----> 4 import plotly.express as px
      5 import plotly

D:\Programs\miniconda\envs\retail-maliks\lib\site-packages\plotly\express\__init__.py in 
      6 __version__ = "0.3.0"
      7 
----> 8 from ._chart_types import (  # noqa: F401
      9     scatter,
     10     scatter_3d,

D:\Programs\miniconda\envs\retail-maliks\lib\site-packages\plotly\express\_chart_types.py in 
----> 1 from ._core import make_figure
      2 from ._doc import make_docstring
      3 import plotly.graph_objs as go
      4 
      5 

D:\Programs\miniconda\envs\retail-maliks\lib\site-packages\plotly\express\_core.py in 
      4 
      5 from _plotly_utils.basevalidators import ColorscaleValidator
----> 6 from .colors import qualitative, sequential
      7 import math
      8 import pandas

ImportError: cannot import name 'qualitative' from 'plotly.express.colors' (D:\Programs\miniconda\envs\retail-maliks\lib\site-packages\plotly\express\colors.py)
```

**Comment by jonmmease** [comment]
Hi @alinastarkov,

Thanks for raising the issue. Unfortunately I'm not able to reproduce it. What version of Python are you using?  Have you tried uninstalling and reinstalling the `plotly` package in a fresh conda environment?

**Comment by alitarraf** [comment]
Turned off my machine, went home, and came back this morning, and the issue disappeared! 
Using python 3.7.3. I will reopen the issue, if I notice it again. Thanks @jonmmease

**Comment by ktd2001** [comment]
any resolution? I'm getting the same error. I have plotly express 0.4.1  installed

ImportError                               Traceback (most recent call last)
<ipython-input-35-86e89bd44552> in <module>
----> 1 import plotly.express as px

~/anaconda3/lib/python3.7/site-packages/plotly/express/__init__.py in <module>
      5 from __future__ import absolute_import
      6 from plotly import optional_imports
----> 7 from ._imshow import imshow
      8 
      9 pd = optional_imports.get_module("pandas")

~/anaconda3/lib/python3.7/site-packages/plotly/express/_imshow.py in <module>
      1 import plotly.graph_objs as go
      2 from _plotly_utils.basevalidators import ColorscaleValidator
----> 3 from ._core import apply_default_cascade
      4 import numpy as np
      5 
~/anaconda3/lib/python3.7/site-packages/plotly/express/_core.py in <module>
      4 
      5 from _plotly_utils.basevalidators import ColorscaleValidator
----> 6 from .colors import qualitative, sequential
      7 import math
      8 import pandas as pd

ImportError: cannot import name 'qualitative' from 'plotly.express.colors' (/home/ktd2001/anaconda3/lib/python3.7/site-packages/plotly/express/colors.py)
