### ISSUE TITLE
Undocumented colormaps

### ISSUE THREAD

**Issue by mattia-lecci** [plotly/plotly_express#124]
Hi, I was trying to decide the best colormap for some of the plots I'm doing, but i found no documentation, not even here:
https://www.plotly.express/plotly_express/colors/
What are the available colors? How can I personalize or reverse them? etc.
Specifically I was looking for a list of colormaps to be used, maybe with colored examples as well?

Thank you for your attention,
Keep up the amazing work!

**Comment by nicolaskruchten** [comment]
At the bottom of https://plotly.express/ you should see a list of all the built in scales and sequences. They can be indexed and reversed like any Python list with `[]`

**Comment by mattia-lecci** [comment]
Thank you for the quick answer. Please consider merging all these information into a single API documentation such as this one:
https://www.plotly.express/plotly_express/index.html
It would be easier for everybody to find it and avoid annoying questions :)

**Comment by nicolaskruchten** [comment]
We now have https://plot.ly/python/builtin-colorscales/ and https://plot.ly/python-api-reference/plotly.express.html :)
