### ISSUE TITLE
Legend covers up plot area

### ISSUE THREAD

**Issue by robroc** [plotly/plotly_express#125]
Plotly Express 0.4.0
Python 3.6
Jupyter Lab 1.0.2
Windows 10
Firefox 68

Legend with many items covers up almost entire plot area. Is there a way to toggle legend or not show it (besides excluding `color` parameter)?

![px](https://user-images.githubusercontent.com/1219001/62243265-f358b500-b3aa-11e9-8a9c-4d94d3f212d3.PNG)

**Comment by robroc** [comment]
Note: on a wide enough monitor, the legend jumps to the right when you go full screen. On smaller screens, this isn't possible.

**Comment by nicolaskruchten** [comment]
Yep, just add `.update_layout(showlegend=False)`
