### ISSUE TITLE
Support using DataFrame index for colors, labels, x, y, etc.

### ISSUE THREAD

**Issue by thatneat** [plotly/plotly_express#126]
I often use the DataFrame index for something meaningful, such as a timestamp corresponding to when the data was taken, or a sequence number. In those cases, it'd be great to be able to use that in plotly express to determine the X value, data color, text label, etc.

Currently the workaround is to copy the index to a separate column, e.g. 

```python
# Contrived example, but this usually comes from some other system
df = pd.DataFrame({'y': [1,2,3]}, index=[4,5,6])
df['x'] = df.index

px.scatter(df, x=px.INDEX, y='y')
```
Instead of having to change the DataFrame, it would be nice if I could just go ahead and do something like
```python
df = pd.DataFrame({'y': [1,2,3]}, index=[4,5,6])
px.scatter(df, x=px.INDEX, y='y')
```
or even, in the special case of using it as an X value, it could be the default:
```python
px.scatter(df, y='y')
```

**Comment by nicolaskruchten** [comment]
We will try to support some version of this in an upcoming release. Most likely not the default behaviour with `x` and most likely not with a special `px.INDEX` value. I'm hoping to accept column/index references directly like `px.scatter(df, x=df.index, y=df.col2)` kind of thing :)

**Comment by thatneat** [comment]
ooh, that sounds great. You could almost make the `df` argument optional then...
In the example you provided, would the x axis label then come from the `df.index.name` attribute or something?

Is there somewhere better for me to follow/comment on your progress towards this, or is this thread the right place to watch?

**Comment by nicolaskruchten** [comment]
It's kind of spread out over a few issues ATM: https://github.com/plotly/plotly_express/issues/37 and https://github.com/plotly/plotly_express/issues/85

**Comment by nicolaskruchten** [comment]
My intention is to create a PR and then update all the relevant issues :) Hopefully in the next month or so!

**Comment by thatneat** [comment]
Awesome. lmk if there's any kind of support I can provide.

**Comment by nicolaskruchten** [comment]
> In the example you provided, would the x axis label then come from the df.index.name attribute or something?

I could do that, yeah, if it's there, otherwise it would default to either "x" or "index" (undecided)

**Comment by nicolaskruchten** [comment]
This will be implemented as part of plotly/plotly.py#1767 ... thanks for the input and patience :)

**Comment by nicolaskruchten** [comment]
We've actually gone farther and implemented full wide-mode support: https://medium.com/plotly/beyond-tidy-plotly-express-now-accepts-wide-form-and-mixed-form-data-bdc3e054f891
