### ISSUE TITLE
Subplots using differnet columns?

### ISSUE THREAD

**Issue by ziliangok** [plotly/plotly_express#127]
For example:
plot1: px.box(df, y='feature1')
plot2: px.box(df, y='feature2')
The facet_row and facet_col can making subplots on one columns, but I want to make subplots on differents columns.

**Comment by nicolaskruchten** [comment]
Plotly Express operates on "tidy data" only, so you will need to reshape your data frame before passing it into `px.box`. This is pretty easy with the `melt()` function in Pandas:

```python
import pandas as pd
df = pd.read_csv(pd.compat.StringIO("""
PlantID,A,B,C,D
1,0,1,2,4
1,3,0,2,0
3,0,0,0,1
4,0,1,1,5
"""))
print(df.head())
```

```
   PlantID  A  B  C  D
0        1  0  1  2  4
1        1  3  0  2  0
2        3  0  0  0  1
3        4  0  1  1  5
```

```python
print(df.melt(id_vars=["PlantID"]).head())
```

```
   PlantID variable  value
0        1        A      0
1        1        A      3
2        3        A      0
3        4        A      0
4        1        B      1
```

Meaning that you can do:

```python
import plotly.express as px
px.box(df.melt(id_vars=["PlantID"]), x="variable", y="value")
```

![image](https://user-images.githubusercontent.com/203523/62294221-78d67680-b438-11e9-8225-bb335f157f04.png)

**Comment by nicolaskruchten** [comment]
Ah sorry, if you want facets per original column it's just:

```python
import plotly.express as px
px.box(df.melt(id_vars=["PlantID"]), y="value", facet_col="variable", boxmode="overlay")
```

![image](https://user-images.githubusercontent.com/203523/62294322-a9b6ab80-b438-11e9-9bfe-835a5264a926.png)

**Comment by ziliangok** [comment]
Thank you! Although this is not what I want, it solve my problems. (●＾o＾●)

**Comment by nicolaskruchten** [comment]
We've actually implemented support for subplots per columns! https://medium.com/plotly/beyond-tidy-plotly-express-now-accepts-wide-form-and-mixed-form-data-bdc3e054f891
