### ISSUE TITLE
Duplicate / overlapping y-axis labels?

### ISSUE THREAD

**Issue by pmaji** [plotly/plotly_express#128]
As Nicolas and I first started [discussing on Twitter here](https://twitter.com/ByPaulJ/status/1157455542719266822?s=20), I have encountered a problem with the `.update_xaxes()` method duplicating the axis labels of faceted axes. 

I have documented this in the 26th cell of [this notebook here](https://nbviewer.jupyter.org/github/pmaji/practical-python-data-viz-guide/blob/master/notebooks/main_lecture_nb.ipynb) which can be found [on GitHub here](https://github.com/pmaji/practical-python-data-viz-guide/blob/master/notebooks/main_lecture_nb.ipynb).

Cell 26 is where I think things are going wrong:

![Screen Shot 2019-08-02 at 9 28 04 PM](https://user-images.githubusercontent.com/25461122/62405525-783efc80-b56c-11e9-998d-47927710ebfe.jpg)

Then, when I remove the lines of code that update the axes, the problem disappears. 

![Screen Shot 2019-08-02 at 9 29 14 PM](https://user-images.githubusercontent.com/25461122/62405538-9efd3300-b56c-11e9-87e0-17c19f7d06fc.jpg)

**Comment by nicolaskruchten** [comment]
Ah ok, you're using `update_yaxes(title="...")` which does just that: updates all the Y axes, of which there are three. You can target this call with `row=1, col=1` to update just the Y axis of the first subplot.

**Comment by pmaji** [comment]
Perfect! Made the change. You rock!

**Comment by nicolaskruchten** [comment]
I should add that you can do two things within your `px` call to get quite close to this output without calling `update_*axes()`:

1. You can provide a `y` variable, in which case your y-axis is labelled `count of <name of y>`
2. You can override the label display with the `labels` kwarg, which will push through the renaming anywhere the label is displayed (so it'll show up in the axis titles)

```python
import plotly.express as px
tips = px.data.tips()
px.histogram(tips, x="total_bill", y="tip", facet_col="sex", labels={"tip": "Tips", "total_bill": "Total Bill"})
```

**Comment by pmaji** [comment]
Very crisp, thank you!
