### ISSUE TITLE
Override of color_discrete_sequence when using sequential integer color tags

### ISSUE THREAD

**Issue by IlyaOrson** [plotly/plotly_express#134]
While using the scatter_3d functionality, I noticed that a discrete color requence gets overridden by the default continuous scale if the color keyword points to a column with sequential integer data instead of categorical data.

Here is a minimum working example of what I mean:

```python
# maybe needed to reproduce from terminal
# import plotly.io as pio
# pio.renderers.default = "browser
import plotly.express as px
iris = px.data.iris()
# iris["species_id"] = [str(id) for id in iris["species_id"]]  # one workaround
fig = px.scatter_3d(
    iris,
    x='sepal_length',
    y='sepal_width',
    z='petal_width',
    color='species_id',  # works as intended with 'species' 
    color_discrete_sequence=px.colors.qualitative.Dark24,
    # color_continuous_scale=px.colors.qualitative.Dark24, # another workaround
)
fig.show()
```

Not sure if this is intended but it got me by surprise.

**Comment by nicolaskruchten** [comment]
Yes, this is intentional: `px` interprets numerical colors as sequential. The recommended way to accomplish what you're looking for would be to cast your numerical color column to a string column.

**Comment by IlyaOrson** [comment]
Got it, I'll close this then. Thanks!
