### ISSUE TITLE
want to use integers to assign discrete colors to markers

### ISSUE THREAD

**Issue by chwang1991** [plotly/plotly_express#140]
![image](https://user-images.githubusercontent.com/39996696/63737544-59a4fa80-c8b9-11e9-9eef-88cc19461196.png)

Hi! 

When I was trying to draw a scatter plot using one column (integer type) to assign discrete colors for the markers, but it automatically consider it as numeric type and use continuous color map instead.

Is there any parameter that can control it?

**Comment by jmiller-dr** [comment]
So basically plotly says "screw you, change all your data because we are too lazy to improve the logic"?

**Comment by nicolaskruchten** [comment]
@jmiller-dr please remain civil. Plotly politely says "one way to achieve your goals would be to convert your integers to strings before plotting".

**Comment by jmiller-dr** [comment]
@nicolaskruchten Just clarifying, didn't mean to lose civility - I assume it just seemed that way as tone is lost via text. My point was just that it seems like a recurring issue that's been around for years and affects a large number of users, thus it would be a well founded feature request for Plotly's backlog, whereas their dismissive response to it undervalues users' time. Again, sorry if I sounded too flippant, I was trying to inject some humor while juxtaposing their dismissive response with the real world impact.

**Comment by nicolaskruchten** [comment]
I'm sorry you felt my response was dismissive, it was not intended as such and you're the first person to voice this perspective. 

Plotly Express explicitly uses the datatype of the input columns as the mechanism by which it determines whether or not a given scale should be continuous or categorical: numbers lead to continuous scales, strings lead to categorical scales. I'm not being dismissive when I say "you can convert numbers to strings", I'm trying to tell you that this is how PX works today. This situation has in fact been around for years, as it's part of the core design of the library, and I'm not sure I agree with you about how many users this impacts, given the low number of comments and reactions to this issue or any related ones. 

In terms of a solution within PX itself, I suppose we could add (yet another) parameter to every single PX function that would allow users to explicitly say "this numerical input should be considered categorical") or we could provide a wrapper much like ~`px.Identity`~ `px.Constant` or `px.Range` or something, e.g. `color=px.Categorical("quality_number")`. It's not high on my priority list as a maintainer, but if it's near and dear to your heart and you want to propose a PR, I'd be willing to chat about it.

**Comment by nicolaskruchten** [comment]
P.S. what I found objectionable about your comment was mostly the implication of "laziness"... Plotly Express exists and is available to all under a very permissive license because of tens of thousands of often-unpaid hours of labour by dozens of fine individuals, none of whom deserve that label or did this work in this spirit of "screw the user".
