### ISSUE TITLE
Plotly express should check if input data is tidy

### ISSUE THREAD

**Issue by matanster** [plotly/plotly_express#141]
Currently, it's easy to run into internal errors like follows:
```
 --> 277  hover_lines = [k + "=" + v for k, v in mapping_labels.items()]
     278  result["hovertemplate"] = hover_header + "<br>".join(hover_lines)
     279  return result, fit_results

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Whereas it would be good to check that the input dataframe is fine before charting, and issue a pinpointed error message rather than fail internally following the dirty python tradition.

**Comment by matanster** [comment]
How to minimally reproduce:

> conda install -c plotly plotly_express==0.4.0

```
lengths = pd.DataFrame(list(range(1000)))
fig = px.histogram(lengths)
fig.show()
```

histo

**Comment by matanster** [comment]
Speaking of tidy, isn't the tidy manifest you link from the docs talking about column names being values and not names?

**Comment by emmanuelle** [comment]
Thank you @matanster, this case should indeed either fail gracefully or be handled correctly. We're in the process of accepting a larger variety of input arguments in `px` (see https://github.com/plotly/plotly.py/pull/1768/), we'll see how to handle your case while working on this PR.

**Comment by nicolaskruchten** [comment]
Indeed, erroring out here is not the right thing.

I believe that code like the following should just result in an empty plot because nothing is being mapped:

```python
import plotly.express as px
import pandas as pd

px.histogram(pd.DataFrame([1,2,3]))
```

**Comment by nicolaskruchten** [comment]
> Speaking of tidy, isn't the tidy manifest you link from the docs talking about column names being values and not names?

I'm not sure what this means :)

**Comment by matanster** [comment]
Thanks for your positive attitude! it seems that in defiance of python tradition, an input-safe library would be even more awesome than what plotly/express already is, especially given that charts need to be developed ad-hoc very typically, by people who don't recall every caveat of the API at the moments when they come to create and choose between plots.

**Comment by matanster** [comment]
Here's where one of the top results for plotly express on google mentions a thing called tidy:

![image](https://user-images.githubusercontent.com/4996067/65261019-0ae12e00-db10-11e9-9378-3f8f66b5822b.png)

And [here's the link](http://www.jeannicholashould.com/tidy-data-in-python.html) for the tidy "manifesto" as much as it matters.

**Comment by nicolaskruchten** [comment]
Oh ok I see what you're referring to. That section header "Column headers are values, not variable names" is actually part of a list of anti-patterns, i.e. what tidy data is *not*, if you look at the paragraph preceding:

![image](https://user-images.githubusercontent.com/203523/65263731-339b0080-dadb-11e9-846b-794cc7259ae7.png)

**Comment by matanster** [comment]
Mmmmm. sorry about that. 
Either way such a lengthy blog post can't be relied upon too much as a resource for how to use a given API. At least not the way that post from 2016 currently is.

**Comment by nicolaskruchten** [comment]
Fair enough.

In any case, we are working on more flexible input types, although the "tidy" philosophy will remain, i.e. you'll still need to concatenate your vectors to do this sort of thing: https://stackoverflow.com/questions/57988604, you just won't be required to stick them into a data frame first :)

**Comment by nicolaskruchten** [comment]
Today, either of these will work:

```python
import pandas as pd
import plotly.express as px

lengths = pd.DataFrame(list(range(1000)))
fig = px.histogram(lengths, x=0)
fig.show()

fig = px.histogram(x=range(1000))
fig.show()
```

**Comment by nicolaskruchten** [comment]
Update: Plotly Express now accepts non-"tidy" data :)

https://medium.com/plotly/beyond-tidy-plotly-express-now-accepts-wide-form-and-mixed-form-data-bdc3e054f891
