### ISSUE TITLE
express plots with "categories" in legend

### ISSUE THREAD

**Issue by K0ertis** [plotly/plotly_express#151]
Hi!

I plot pandas dataframe with a "lot" of data

```
fig = px.line(df,
                x='time [s]',
                y="data [V]",
                line_group="group",
                color='pixel',
                line_dash='group',
                facet_col="int_times [µs]",
                facet_row="gain [1]"
                )
```
group has 4 elements and pixel has 64 elements which results to a legend which has 256 entries. Would it be possible to just add the type of the legend, like 
- pixel [1:64] -> 64 colors
- line _group [1:4]
  dash -> group0
  dot -> group1
  dash-> group2
  longdash->group3

So in total there are 68 elements instead of 256, and each data is accessible by clicking to the right pixel/linestyle

**Comment by nicolaskruchten** [comment]
This is a good idea which will be implemented once https://github.com/plotly/plotly.js/issues/5099 is implemented, so I'll close as duplicate for now.
