### ISSUE TITLE
Strange behavior when adding another trace

### ISSUE THREAD

**Issue by Juanlu001** [plotly/plotly_express#156]
As recommended [in this community thread](https://community.plot.ly/t/multiple-traces-plotly-express/23360), I am using this code to create a line plot with Plotly Express and then adding another trace on top of it:

```python
df = pd.DataFrame({
    "a": [1, 2, 3, 4],
    "b": [1, 4, 8, 16],
})
fig = px.line(df, y="a")
fig.add_scatter(y=df["b"], name="b", mode="lines")
```

However, in the resulting figure, the first line cannot be toggled using the legend:

![Screenshot_2019-10-27 JupyterLab(1)](https://user-images.githubusercontent.com/316517/67642087-949ecb00-f908-11e9-8daa-6ed053bf297d.png)

**Comment by nicolaskruchten** [comment]
The new recommended way of doing this is actually as follows:

```python
import pandas as pd
import plotly.express as px
df = pd.DataFrame({
    "a": [1, 2, 3, 4],
    "b": [1, 4, 8, 16],
})
px.line(df.melt(), y="value", color="variable")
```

**Comment by nicolaskruchten** [comment]
Which gives this output:

![image](https://user-images.githubusercontent.com/203523/67652184-12f76f00-f901-11e9-8ddc-27bf2c409f5c.png)

**Comment by Juanlu001** [comment]
Looks like `.melt` is exactly what I needed (and in fact I had implemented a poor version of it before the discovery). Thanks a lot!

Regarding this issue in particular, I leave it to the opinion of the core devs whether to close it or not.

**Comment by nicolaskruchten** [comment]
Great!
