### ISSUE TITLE
range_theta in polar plots would be nice

### ISSUE THREAD

**Issue by elena-pascal** [plotly/plotly_express#160]
The APIs for line_polar and scatter_polar list an option for range_r but not range_theta. graph_objects had sector and matplotlib has limits to do that. I would like to only look at a section of the circle and I don't know how to do that in express. I might be missing something.

**Comment by nicolaskruchten** [comment]
Thanks for reporting this! It's an embarrassing oversight and will be fixed in the next release :)

Here's the PR: https://github.com/plotly/plotly.py/pull/1969

**Comment by elena-pascal** [comment]
Very nice! Thank you for sorting it out. I'm looking forward to using it. Happy to close
