### ISSUE TITLE
TypeError: imshow() got an unexpected keyword argument 'x'

### ISSUE THREAD

**Issue by sorenwacker** [plotly/plotly_express#167]
`plotly.express` is now developed inside the `plotly.py` library, please open
your issue on https://github.com/plotly/plotly.py/issues/new

According to https://plotly.com/python/heatmaps/ px.imshow() should accept arguments x,y and labels. But when I try that I receive 

TypeError: imshow() got an unexpected keyword argument 'x'

Using plotly_express 0.4.1

**Comment by nicolaskruchten** [comment]
Hi there! You'll need to upgrade your installation of `plotly` to get this keyword argument to work. All that the `plotly_express` package does these days is re-export `plotly` functions :)

**Comment by sorenwacker** [comment]
Which version should be installed then? Thanks!!

**Comment by nicolaskruchten** [comment]
plotly 4.8.0 came out today so I would recommend that one :)

**Comment by sorenwacker** [comment]
Ok, thank you!
