### ISSUE TITLE
Bivariate distribution dependency

### ISSUE THREAD

**Issue by shakasom** [plotly/plotly_express#18]
Plotting bivariate distributions with scatter plot combined with box/violin plots throws dependency error. 

ModuleNotFoundError: No module named 'patsy'

Environment: Windows 10
Statsmodels: 0.9.0
Scipy: 1.1.0
pandas: 0.24.2
Plotly: 3.7.1

**Comment by empet** [comment]
@shakasom  I had the same issue, but installing `statsmodels` for python 3.7.1 fixed it.

 `conda install -c conda-forge statsmodels`

performed the following replacement:
`0.9.0-py36hfa6e2cd_1000 --> 0.9.0-py37hfa6e2cd_1000`

and upgraded `patsy` to `patsy-0.5.1`

**Comment by nicolaskruchten** [comment]
Ah right, I forget that installing `statsmodels` doesn't always install its dependencies. I'll add this stuff to `setup.py` tomorrow and push to PyPI again :)

Thanks for letting me know!

**Comment by shakasom** [comment]
Thanks @empet I installed patsy with pip and everything worked.
