### ISSUE TITLE
Facet wrapping

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly_express#2]

**Comment by kmader** [comment]
Definitely interested in this feature, also having different scales for different facets. I didn't immediately see how to do this.

**Comment by nicolaskruchten** [comment]
Indeed, we don't have a free-scales feature at the moment, but we can look at adding it when we add facet-wrapping.

**Comment by sakethsaxena** [comment]
Hey!
I recently started using plotly express, just wondering if there is any momentum on this feature yet? 

I was trying to generate a facetted scatter plot using a single dimension/column which has about 80-90 unique entries using `facet_col` in `px.scatter()` but it throws a value error.

**Comment by joelostblom** [comment]
I am also very interested in having the equivalent of seaborn's `col_wrap` parameter. In the meantime, is there any workaround for achieving this behavior with plotly express? I regularly need to plot > 10 subplots and don't have another variable to use for row facetting.

**Comment by chriddyp** [comment]
Could you introduce a new column("`row_number`") into your data frame that would be used to break apart into rows?

**Comment by joelostblom** [comment]
@chriddyp Thanks for the suggestion, that would work around the problem for my own visualization needs. 

One of the reasons I am interested in plotly express is for teaching people new to programmatic data visualization. For this purpose it would be great if there is a wrapping parameter, since that would be easier to understand.

**Comment by joelostblom** [comment]
Hmm, maybe I misunderstood the proposed workaround initially... I just tried adding row numbers to simulate `col_wrap=3` and ended up with the plot below:

![image](https://user-images.githubusercontent.com/4560057/67139102-f53f5100-f200-11e9-891c-f4b04f9d064b.png)

Initially, I thought that empty columns would be removed and wrapped around like in this mockup:

![image](https://user-images.githubusercontent.com/4560057/67139155-a80faf00-f201-11e9-9e76-148f8b063d32.png)

The current plotly express behavior makes more sense than what I was thinking, but I am suspecting this means I misunderstood what you meant when you proposed the workaround @chriddyp and @nicolaskruchten. In this example, how would you add row numbers to the "Sun, Sat, Thur, and Fri" observations to achieve the desired wrap around behavior?

**Comment by nicolaskruchten** [comment]
Yeah... This is going to be a pretty rough workaround until we implement this for real: you'd have to provide your own row *and* column, and on top of that you wouldn't get per-subplot titles, you'd be stuck with the per-column and per-row "row_number=1" type labelling, unless you added your own annotations.

**Comment by nicolaskruchten** [comment]
OK, I've got a working version of PX with a new `facet_num_cols` kwarg that results in this (and is incompatible with `facet_row` and `marginal*`... should be in the next version of `plotly`! Thanks for the nudge :)

![image](https://user-images.githubusercontent.com/203523/67177667-62c7ba80-f384-11e9-812d-2cb9b28700a8.png)

**Comment by joelostblom** [comment]
Beautiful! Thanks for your responsiveness!
