### ISSUE TITLE
Possible to change opacity (alpha of matplotlib)?

### ISSUE THREAD

**Issue by gepcel** [plotly/plotly_express#20]
Is it possible to change alpha? For example `px.scatter(alpha=0.7)`?

**Comment by ismailuddin** [comment]
#22 
I've made a pull request to add support for the `opacity` argument to the  scatter functions:
- `px.scatter()`
- `px.scatter_3d()`
- `px.scatter_matrix()`
- `px.scatter_ternary()`
- `px.scatter_polar()`

## Usage
```
px.scatter(df, x='column1', y='column2', opacity=0.5)
```

Not sure if the some of the other functions could benefit from this argument too?

**Comment by nicolaskruchten** [comment]
Closed via community PR #22 !
