### ISSUE TITLE
Mapbox tiles

### ISSUE THREAD

**Issue by shakasom** [plotly/plotly_express#27]
is there a possibility to add Mapbox tiles. we have only the default option for a base map but there are different basempas available in Mapbox. Like Folium python library implements it: here is an example http://python-visualization.github.io/folium/quickstart.html 

I am not sure how complex it is to implement.

**Comment by nicolaskruchten** [comment]
There is support for this in the underlying library so it shouldn't be too hard to implement in PX eventually. If you want to switch tileset, you can add `.update(layout={"mapbox":{"style": "satellite-streets"}})` after the `px.scatter_mapbox()` call.

Here are the docs for that attribute: https://plot.ly/python/reference/#layout-mapbox-style

**Comment by shakasom** [comment]
That is great. Thanks, @nicolaskruchten for the tip.

**Comment by nicolaskruchten** [comment]
Happy to help!
