### ISSUE TITLE
I have problems when I use plotly_express

### ISSUE THREAD

**Issue by doublesunshine** [plotly/plotly_express#28]
When I use plotly_express on Python 3.7 alone, when you call the above code, the image doesn't jump out automatically, and Python automatically closes.
Excuse me, can this module not be used alone? Need to install plotly?

**Comment by nicolaskruchten** [comment]
Can you provide a bit more information about the code you're running that's not working?

To your second question: yes, the `plotly` module is a required dependency.

**Comment by doublesunshine** [comment]
@nicolaskruchten  I had a misunderstanding at the time and it doesn't exist now.
I found that he needed the jupyter software to open it.
I found that I want to use this px. I need to download the jupter and learn to use the jupter. This makes me less satisfied, because I use this module for convenience and simplicity, but I need to spend more time learning.

**Comment by nicolaskruchten** [comment]
OK, great!
