### ISSUE TITLE
Add confidence interval bootstrap plot

### ISSUE THREAD

**Issue by robotenique** [plotly/plotly_express#31]
In seaborn, when we use `sns.pointplot`, it calculates the confidence interval using a simple bootstrap if there's multiple values for a given x, and it's very handy. I think it would be awesome if plotly express could do something like that in an easy manner. Currently I have to calculate individually and manually these confidence intervals to plot in plotly.

This is an example of a pointplot:
http://mitalbalar.com/img/output_29_0.png

**Comment by nicolaskruchten** [comment]
Thanks for the suggestion!

This is an area where Plotly Express will likely not go as far as Seaborn into the stats/modelling piece of things versus just displaying the data it's given... I want to avoid issues of reproducibility/telling people how to model their data as much as possible :)

**Comment by wjaskowski** [comment]
The lack of seaborn-like interface for plotly has been stopping me for using plotly for a long time - now it is! - but some confidence intervals (like bootstrapping) are a must - this is should be very simple.

**Comment by nicolaskruchten** [comment]
I'm going to close this issue in favour of https://github.com/plotly/plotly.py/issues/2418 wherein we will (someday!) add the ability for folks to plug in their own confidence-interval calculations.
