### ISSUE TITLE
No attribute 'TitleValidator'

### ISSUE THREAD

**Issue by spencerlawrence36** [plotly/plotly_express#33]
AttributeError: module '_plotly_utils.basevalidators' has no attribute 'TitleValidator'

Code: 
`df = pd.DataFrame(np.random.randn(100, 2), columns=list('AC'))`
`px.scatter(df, x='A', y='C')`

I upgraded plotly but received the same error

**Comment by nicolaskruchten** [comment]
Which version of `plotly` are you using now?

**Comment by spencerlawrence36** [comment]
plotly==3.7.1
plotly-express==0.1.3

**Comment by nicolaskruchten** [comment]
Hmmm it seems like you have a problem with your `plotly` installation. What does `plotly.__version__` contain in the same environment as you're seeing this problem?

It's sometimes possible to have multiple versions of `plotly` installed at different versions e.g. one with `pip` and one with `conda` and this can lead to strange behaviour.
