### ISSUE TITLE
Blank charts

### ISSUE THREAD

**Issue by jig78** [plotly/plotly_express#34]
Hello All, 

I am using Jupyterlab and I have installed plotly_express and the jupyterlab/plotly-extension successfully. I also have installed pdoc3>=0.5.3 & nbconvert>=5.3.1. I tried running the plotly express walkthrough (gapminder data) and I am getting a blank screen when I run the code below? No errors or any output? Do I need to install anything else? 

import plotly_express as px
gapminder = px.data.gapminder()
gapminder2007 = gapminder.query("year == 2007")

px.scatter(gapminder2007, x="gdpPercap", y="lifeExp")

Any help would be appreciated! Thanks.

**Comment by josesho** [comment]
I am seeing this as well. The output cell just gives a blank.

**Comment by josesho** [comment]
Hi @jig78 , I figured it out. (It was on the README all along? haha)

Simply run

```shell
jupyter labextension install @jupyterlab/plotly-extension
```

in your terminal, and restart Jupyterlab.
