### ISSUE TITLE
Plotly.js 1.46 -> Plotly.py 3.8 -> PX 0.2

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly_express#35]
- [x] hover_extra #6 
- [x] hovertemplate on box/violin/marginals
- [x] barmode on bars
- [x] barmode=stack on histograms
- [ ] fix ordering on 3.5-
- [ ] `px.strip()` ?
- [ ] `px.sunburst()`?

**Comment by happyshows** [comment]
Hi, is sunburst still on the plan?

**Comment by nicolaskruchten** [comment]
Yes, we will eventually support all Plotly trace types :)
