### ISSUE TITLE
Consider removing column name and = sign in legend

### ISSUE THREAD

**Issue by mazzma12** [plotly/plotly_express#36]
Hi again @nicolaskruchten,

Something that puzzled me about the `color` arg in the plot is that it includes the name of the column followed by an equal sign. Would you consider removing it and just let the value of the column in place? Here are a few reasons to support that point : 
* It is not displayed in plotly by default
* It's redundant information when we see `date=` or`country=` it easy to infer by the value of the field
* It takes some extra place, that is valuable, especially in the vertical orientation. 

![image](https://user-images.githubusercontent.com/23187108/55218808-769eaa00-5203-11e9-95b6-94598ac4ee6c.png)

Also, for personal taste, I think equal sign does not play well outside equations and prefer `:` instead.

Happy to discuss with you about it. Maybe there is an option that can disable it, that I am not aware of.

**Comment by nicolaskruchten** [comment]
Thanks for the input!

This is the best compromise I could find at the moment for dealing with cases where in fact it's not easy to infer from the value (i.e. the values are "Yes" and "No" and the column is called "Smoker" etc) and because when you are using colours and symbols, you need to be able to differentiate which is which ("smoker=Yes, child=Yes" vs "Yes, Yes").

The best way to deal wit this would be to have separate legends for color, symbol, size and line-dash, with titles, but plotly.js doesn't (yet) support this kind of thing.

In terms of how to actually get the effect you want, unfortunately you'll have to iterate through the traces and change the names. We're looking at various ways to make that easier: https://github.com/plotly/plotly.py/issues/1484

**Comment by mazzma12** [comment]
Hi @nicolaskruchten eventually I found the time to reply!

> This is the best compromise I could find at the moment for dealing with cases where in fact it's not easy to infer from the value (i.e. the values are "Yes" and "No" and the column is called "Smoker" etc) and because when you are using colours and symbols, you need to be able to differentiate which is which ("smoker=Yes, child=Yes" vs "Yes, Yes").

From my experience, such ambiguity would be limited as the graph would come with a title s.a *evolution by smoking behaviour*. But I hadn't realized you could have composed categories, in this case, I understand that might be tricky. 

> The best way to deal wit this would be to have separate legends for color, symbol, size and line-dash, with titles, but plotly.js doesn't (yet) support this kind of thing.
Do you mean having a title for each legend section like in theseaborn API for [categorical data](https://seaborn.pydata.org/tutorial/categorical.html)? I think that was the reference I had in mind when opening the issue, too bad!

**Comment by nicolaskruchten** [comment]
With the newest release, you can now easily change this after the fact with something like:

`.for_each_trace(lambda t: t.update(name=t.name.replace("=",": ")))`

For example:

![image](https://user-images.githubusercontent.com/203523/57308430-568cc100-70b4-11e9-93fe-745b58bf9838.png)

**Comment by nicolaskruchten** [comment]
You could of course use this to edit any property etc.

**Comment by prateekshrivastav786** [comment]
If you just want to show the values in legend, you can use this:
```
fig = px.scatter(data_grouped_month, x="resolved_tf", y="alert_role",
                 size='incident_count',color='alert_role', hover_data=['alert_role']).for_each_trace(lambda t: t.update(name=t.name.split("=")[1]))
```

like if you have something like:
```
alert_role=cpu
alert_role=clone
alert_role=memory
alert_role=io wait time
alert_role= databse
```
Like:
<img width="334" alt="Screenshot 2020-02-19 at 12 39 27" src="https://user-images.githubusercontent.com/35179248/74835316-f3071380-5314-11ea-810c-023eecd4f3e7.png">


so the below snippet will remove the "alert_role" and will show only values like cpu, clone,memory etc:
`.for_each_trace(lambda t: t.update(name=t.name.split("=")[1]))`

The output will be:
```
cpu
clone
memory
io wait time
database
```

![Screenshot 2020-02-19 at 12 31 58](https://user-images.githubusercontent.com/35179248/74835136-a3284c80-5314-11ea-8296-603b0114b4aa.png)

**Comment by nicolaskruchten** [comment]
This is actually no longer necessary... As of Plotly.py 4.5, Plotly Express no longer puts the `=` in trace names, because legends support titles.

**Comment by tconnor23** [comment]
Love the update to the legend in 4.5! Now I'm wondering if there's a way to supress the '=' expression from the titles of sub-plots. or if not, is there a helper function like there used to be for traces, something like:

for_each_subplot( lambda z: z.update(title=z.title[(z.title.find("=")+1):]))

i.e. want to remove the highlighted part
![image](https://user-images.githubusercontent.com/41125521/75042831-0b9a3980-548d-11ea-9d84-45cb3791949c.png)

**Comment by nicolaskruchten** [comment]
Yep:

```python
import plotly.express as px

fig = px.scatter(px.data.tips(), x="total_bill", y="tip", facet_col="smoker")
fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
fig.show()
```

**Comment by nicolaskruchten** [comment]
@jdamiba can you add this example to the facet docs please? ☝️

**Comment by anuraghuram** [comment]
Similarly, is there a way to hide the facet_col appearing as a header above subplots?

**Comment by tabeacodes** [comment]
Hey, is there a way to set the x and y axis label for every subplot?

**Comment by KeithWM** [comment]
> Yep:
> 
> ```python
> import plotly.express as px
> 
> fig = px.scatter(px.data.tips(), x="total_bill", y="tip", facet_col="smoker")
> fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
> fig.show()
> ```

This is a working solution of course, but it seems odd for this hack to be necessary.
