### ISSUE TITLE
x polymorphism for  index and series type

### ISSUE THREAD

**Issue by yytsui** [plotly/plotly_express#37]
This will be useful for time series data.
Instead of copy time index to a column:

> df['time'] = df.index
> px.line(df, x='time', y='value')

it will be more convenient that we can do this directly: 

> px.line(df, x=df.index, y='value')

Thank you for this great library!

**Comment by jonmmease** [comment]
One consideration here is that plotly_express needs a name associated with each column for things like axis labels and hover tooltips.

Pandas index levels can optionally have names, and I would be in favor of having plotly_express search the index levels if a specified name doesn't show up as a column.

If the index doesn't already have a name then a name would need to be assigned, but this doesn't require duplicating data and I'd argue that it's a reasonable thing to do even apart from visualization.

Something like...
```
df.index.name = 'time'
px.line(df, x='time', y='value')
```

**Comment by nicolaskruchten** [comment]
Interestingly, we could actually take things a bit farther: consider something `px.line(df, x=df.index, y=df.cool_column)`. Given `df`, `px` could internally try to do equality checks on the columns and the index (assuming first col of index, say) and retrieve the names from `df`. This would allow-but-not-require `Series` to be passed in, thereby enabling some nice auto-complete behaviour... not just strings any more!

**Comment by mazzma12** [comment]
Hi there,

Just joined the issue, as I was talking about it somewhere else. As I mentioned it already, I suggest to call `reset_index()` on the series, WDYT ?

> It's actually quite easy to grab the `x` and `y` column names from the series `ts' by doing `x=ts.index.name` and `y=ts.name`. Then when you call `ts.reset_index()` it will return a new dataframe object with columns  `[x, y]`

**Comment by nicolaskruchten** [comment]
I don't really want to accept arbitrary `Series` as inputs here, I'd rather they belong to `df`, as anyway I'm using `df.groupby()` under the hood

**Comment by nicolaskruchten** [comment]
This will be implemented as part of plotly/plotly.py#1767 ... thanks for the input and patience :)

**Comment by prasadsonar2** [comment]
what kind of datatypes supported to plotly

**Comment by nicolaskruchten** [comment]
@prasadsonar2 here is the documentation on input arguments for Plotly Express: https://plot.ly/python/px-arguments/
