### ISSUE TITLE
px.table()

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly_express#41]
See beginning of conversation at  https://github.com/plotly/plotly.py/issues/1485

**Comment by dhirschfeld** [comment]
I'm confused why this issue was closed? The linked plotly issue seemed to suggest this was a good fit for `plotly_express`?

**Comment by nicolaskruchten** [comment]
Yes, but PX is now part of Plotly.py so the other issue is the main issue for this idea. I'm gradually phasing out this plotly_express repo and it's issues basically.

**Comment by dhirschfeld** [comment]
> *Plotly Express is now part of Plotly.py version 4 and so the `plotly_express` module now just re-exports the contents of `plotly.express`*

Should've read the docs! 🤦 
Thanks for the pointer and sorry for the noise...

**Comment by nicolaskruchten** [comment]
No worries!
