### ISSUE TITLE
Error on all plots: "TypeError: iplot() got an unexpected keyword argument 'auto_play'"

### ISSUE THREAD

**Issue by efonda** [plotly/plotly_express#43]
When trying to create any plot, even those from the example page, I receive the error: `TypeError: iplot() got an unexpected keyword argument ‘auto_play’`. I tried both in jupyter-lab and jupyter notebook. Normal plotly works fine.

Python 3.7.2 - plotly 3.7.1 - plotly_express 0.1.3 - jupyterlab 0.35.4 - jupyter 4.4.0

**Comment by efonda** [comment]
The full error is 
`
import plotly_express as px
iris = px.data.iris()
px.density_contour(iris, x="sepal_width", y="sepal_length")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    916             method = get_real_method(obj, self.print_method)
    917             if method is not None:
--> 918                 method()
    919                 return True
    920 

/usr/local/lib/python3.7/site-packages/plotly_express/_core.py in _ipython_display_(self)
     36             init_notebook_mode()
     37             ExpressFigure.offline_initialized = True
---> 38         iplot(self, show_link=False, auto_play=False)
     39 
     40 

TypeError: iplot() got an unexpected keyword argument 'auto_play'`

**Comment by nicolaskruchten** [comment]
Hmmm it seems like you have a problem with your `plotly` installation. What does `plotly.__version__` contain in the same environment as you're seeing this problem?

It's sometimes possible to have multiple versions of `plotly` installed at different versions e.g. one with `pip` and one with `conda` and this can lead to strange behaviour.

**Comment by efonda** [comment]
You were right, there were two version of plotly installed. Thank you

**Comment by nicolaskruchten** [comment]
Great!

**Comment by ghost** [comment]
I'm facing this issue when I'm executing iplot() in Jupyter lab and Jupyter Notebook
"Authentication credentials were not provided"
