### ISSUE TITLE
in scatter plot, the values of column 'datetime' are totally different from original data

### ISSUE THREAD

**Issue by r41350** [plotly/plotly_express#44]
hello :
  When using code in jupyter notebook,
import plotly_express as px
px.scatter(datanew, x='datetime', y="vol",range_y=[0,200],hover_name='vol')
the values of column 'datetime' in figure is totally different datetime. all datetime values are earlier 8hour.

python version
'3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]'

datanew.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1904 entries, 0 to 1903
Data columns (total 10 columns):
datetime    1904 non-null datetime64[ns]
vol         1904 non-null int32

datanew['datetime']
0      2019-03-11 09:31:00
1      2019-03-11 09:32:00
.......
1902   2019-03-20 14:57:00
1903   2019-03-20 15:00:00
Name: datetime, Length: 1904, dtype: datetime64[ns]

in the Figure, all datetime values are earlier 8hour
such as:
2019-03-11 09:31:00 became 2019-03-11 01:31:00

how to deal with the issue, may be time zone issue?
thanks

**Comment by nicolaskruchten** [comment]
Yes, this is a known issue in Plotly.py and will be fixed in the upcoming v4... See https://github.com/plotly/plotly.py/issues/209 for more details!

**Comment by r41350** [comment]
> Yes, this is a known issue in Plotly.py and will be fixed in the upcoming v4... See [plotly/plotly.py#209](https://github.com/plotly/plotly.py/issues/209) for more details!

thank you for your information! waiting for your update

**Comment by r41350** [comment]
> Yes, this is a known issue in Plotly.py and will be fixed in the upcoming v4... See [plotly/plotly.py#209](https://github.com/plotly/plotly.py/issues/209) for more details!

thank you for your information! waiting for your update
