### ISSUE TITLE
Int columns starting at 0 conflict with dataframe index 

### ISSUE THREAD

**Issue by mazzma12** [plotly/plotly_express#49]
## How to reproduce : 

```python
import plotly_exopress as px

columns = ['sepal_length', 'sepal_width']
iris = px.data.iris()[columns]
px.scatter(iris, 'sepal_length', 'sepal_width')
```
![image](https://user-images.githubusercontent.com/23187108/55816739-53250a80-5af3-11e9-9863-7bb3b79764fe.png)

```python
# Changing colnames to int
iris.columns = [0, 1]
px.scatter(iris, 0, 1)
```
![image](https://user-images.githubusercontent.com/23187108/55816749-58825500-5af3-11e9-9fdd-94244ec102fa.png)

As you can see the index of the dataframe is taken as the x axis in the last case

**Comment by nicolaskruchten** [comment]
Right now the docs say that `x`, `y` and friends only accept strings, so I'm not surprised there's some odd behaviour in other cases :) What is the common use-case for renaming your columns with integers? With `px` you lose much of the benefit of auto-labelling of axes, legend entries, hover labels etc.

**Comment by mazzma12** [comment]
Sure it's true. I know it might seem odd to cast columns with integers, but this is actually the default behavior of pandas when creating a dataframe without column names : 
```python
import pandas as pd
import numpy as np

df = pd.DataFrame(np.arange(10).reshape((5, 2)))
df.columns
Out [0] RangeIndex(start=0, stop=2, step=1)
df[0] # yields the first column
```

I know it sounds odd, but it might easily lead to confusion -I have no clue how to deal with that thoug.

**Comment by nicolaskruchten** [comment]
I've added stricter validation and nicer error messages to v0.1.8 such that integers will no longer be accepted as inputs... Column references must now actually be present in `df.columns` in order to be accepted.
