### ISSUE TITLE
secondary Y-axes

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly_express#5]

**Comment by iceriverho** [comment]
secondary Y-axes is needed,
please!!!

**Comment by nicolaskruchten** [comment]
Yep, we're thinking about how to do this! One big problem is how to handle facets and marginals... do we just say that secondary axes are incompatible?

**Comment by helloitsjulian** [comment]
Any update on how to add a secondary axis?

**Comment by maarten-betman** [comment]
Any update on adding secondary y-axis?

**Comment by nicolaskruchten** [comment]
Closing in favour of https://github.com/plotly/plotly.py/issues/2648
