### ISSUE TITLE
Plotly_express in a function or if-else statement

### ISSUE THREAD

**Issue by qbb-work** [plotly/plotly_express#50]
Hi,
plotly_express works perfectly for me within one cell. Now, I'm trying to put it inside a function and/or plot different graphs depending on the user input. As such, I'm putting two different plot functions within an if-else statement. For example,

example 1:

def f (data):
      px.bar (data)

f (data)

example 2:

ip = input("Please input a or b")

if ip == 'a':
       px.bar (......)
else:
      px.histogram (....)

However, nothing shows up. Is this normal? Is there a way to work around it? 

Thanks so much.

Regards,
Ken Chen

**Comment by nicolaskruchten** [comment]
Hi!

Ah yes, this is a bit tricky/too implicit: the figures are rendered by default in Jupyter if they're the last statement in the cell, so if you want to do this you can do 

```python
if condition:
    fig = px.bar()
else:
    fig = px.histogram()

fig
```


Alternatively, you could call `IPython.display.display()` like this:

```python
from IPython.display import display

if condition:
    display(px.bar())
else:
    display(px.histogram())

#some other code here
```

**Comment by qbb-work** [comment]
Thanks. Very helpful. Problem solved
