### ISSUE TITLE
Add line to a bar graph

### ISSUE THREAD

**Issue by EY-work** [plotly/plotly_express#51]
Hi,

I'm wondering whether I can add a line to a bar chart and display the value in a secondary y-axis (on the right). In other words, I'm trying to combine two plot types into the same plot. Thanks very much.

**Comment by nicolaskruchten** [comment]
You can do this by adding traces to the Figure object returned by `px` using the normal `plotly` methods like `.add_trace()` or `.update()`. We're working on a way to merge two `px`-produced `Figure`s together to do this, but that API isn't ready yet.

**Comment by nicolaskruchten** [comment]
Closing in favour of https://github.com/plotly/plotly.py/issues/2648

**Comment by harxish** [comment]
Hey @nicolaskruchten ,

> You can do this by adding traces to the Figure object returned by px using the normal plotly methods like `.add_trace()` or `.update()`. We're working on a way to merge two px-produced Figures together to do this, but that API isn't ready yet.

Is the API ready yet ? or is there any workaround for overlaying `px.timeline` and `px.scatter`.

Thanks.

**Comment by nicolaskruchten** [comment]
No, https://github.com/plotly/plotly.py/issues/2648 is still open.
