### ISSUE TITLE
title not centered

### ISSUE THREAD

**Issue by rpanai** [plotly/plotly_express#52]
I experienced a different behaviour in title alignment in `plotly` and `plotly_express` inthe first case the title is centered while in the second case is aligned to the left. The code for centered title in `plotly` is [here](https://stackoverflow.com/a/55652609/4819376) while if try with `plotly_express` as
![newplot](https://user-images.githubusercontent.com/21178372/56042164-6b21a780-5d08-11e9-8d7b-96f42b8582cf.png)

```python
import pandas as pd
import plotly_express as px
px.scatter(df, x="gdp_percap", y="life_exp", color="continent",
           range_x=[0,50_000], range_y=[0,90], hover_name="country",
           title='Life Expectancy v. Per Capita GDP, 2007')
```

![newplot (2)](https://user-images.githubusercontent.com/21178372/56042176-72e14c00-5d08-11e9-8117-2026381c2da7.png)

**Comment by nicolaskruchten** [comment]
Yes, the Plotly Express template has right-aligned titles. 

You can call `.update(layout=dict(title=dict(x=0.5)))` on the output of your `px.scatter()` call to change this setting in the resulting figure.

**Comment by mauricio-ocampo** [comment]
you can also change it + the font size with this: `.update_layout(title_font_size=16, title_x=0.5)` at the end of your `px.scatter()` call
