### ISSUE TITLE
draw median for all visible traces

### ISSUE THREAD

**Issue by rpanai** [plotly/plotly_express#53]
This come to my mind after working on this [question](https://stackoverflow.com/q/55586773/4819376)  on SO. The given case has an answer in dash as long as I have a trace for all possible case. In this case there are just 3 possibilities, option A, option B and both. But if I have `n` traces it turns out there are `2^n-1` possibilities. So produce all the traces for the median could be tedious. Is there a possibility to add a similar feature? Just to be clear I'm looking for a possible way to contribute to this project.

**Comment by nicolaskruchten** [comment]
I don't think this is a common-enough thing to want to do that I would add an argument just for this... That said, `px.box()` and `px.violin()` are both capable of showing medians and generally better-suited to visualizing distributions. In fact, for `px.scatter()` you can use `marginal_x` and `marginal_y` to add marginal box plots which will show you the median already.
