### ISSUE TITLE
colorbar and legend can overlap

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly_express#54]
When using continuous color and symbols, say

![image](https://user-images.githubusercontent.com/203523/56162694-a3d8af80-5f9a-11e9-9104-bb40ab1fda10.png)

**Comment by HugoDel** [comment]
Hello, I have the same problem. Any update ?

**Comment by nicolaskruchten** [comment]
We don't really have line-of-sight on an automatic mode to avoid this... The best I can give you for now is that you can shrink the color bar: https://plot.ly/python/colorscales/#hiding-or-customizing-the-plotly-express-color-bar

**Comment by HugoDel** [comment]
Thank you for the documentation! Ok the automatic mode, it's not a problem to specify the height in my case.

**Comment by samueldemir** [comment]
A solution could be by changing the position of the legend:

`fig.update_layout(legend_orientation="h")`

as mentioned in https://plotly.com/python/legend/

**Comment by ErinKenna** [comment]
Or changing the position of the color bar. 
`fig.update_layout(coloraxis_colorbar=dict(orientation="h"))`
