### ISSUE TITLE
Cannot plot violin/box plots in Jupyter Noteboook

### ISSUE THREAD

**Issue by bmcconeghy** [plotly/plotly_express#55]
Hi there,

Just started using plotly express and I'm loving the interactivity of it! It works perfectly for my scatter plots I've created so far, but unfortunately does not work for violin or box plots.

Here is my set up:
Anaconda Navigator 1.9.7
Jupyter Notebook 5.7.8
Python 3.7.3
Plotly 3.7.0
Plotly Express 0.1.5

The error is:
``ValueError: Invalid property specified for object of type plotly.graph_objs.Violin: 'hovertemplate'``

This even occurs when i try to replicate the example from https://www.plotly.express/ (see screenshot below)
``tips = px.data.tips()
px.violin(tips, y="tip", x="smoker", color="sex", box=True, points="all")``

Thanks for the help!
Brian

![image](https://user-images.githubusercontent.com/38894122/56173489-a6d79e00-5fa2-11e9-8112-a30322007638.png)

**Comment by jonmmease** [comment]
Hi @bmcconeghy, I think you need to update your version of plotly.py to 3.8.0, which was released today (yeah, things are still moving pretty fast :slightly_smiling_face:)

**Comment by nicolaskruchten** [comment]
Ah apologies, I didn’t bump the version dependency in setup.py!

**Comment by nicolaskruchten** [comment]
I've just pushed plotly express version 0.1.6 to PyPI with the corrected dependency, and it'll be up on conda in a sec.

**Comment by bmcconeghy** [comment]
OK, I've updated it now and it seems to be working! Thanks @jonmmease and @nicolaskruchten 
Cheers,
Brian
