### ISSUE TITLE
Title does not render in VSCode based Jupyter notebooks

### ISSUE THREAD

**Issue by swayson** [plotly/plotly_express#56]
Despite setting the title argument, the displayed graphic does not appear to illustrate the title.

![image](https://user-images.githubusercontent.com/1834241/56200903-fe781700-603f-11e9-9cd3-22a9acc268e4.png)

VS Code: 1.33.1
Python ext:  2019.3.6558
plotly_express: 0.1.3

**Comment by nicolaskruchten** [comment]
Unfortunately VSCode has an older version of plotly.js baked in and so Plotly Express plots won't look right until this is fixed... We're working on getting this resolved but it might be a little while :)

See https://github.com/Microsoft/vscode-python/issues/4953 and the upstream https://github.com/nteract/minimal-plotly/issues/13

**Comment by jonmmease** [comment]
See https://github.com/Microsoft/vscode-python/pull/5428 for progress!
