### ISSUE TITLE
'method' object is not subscriptable - Normal Excel File

### ISSUE THREAD

**Issue by tolandwehr** [plotly/plotly_express#60]
Hi there, 

hope that this issue is not redundant. I'm trying to visualize data in a similar fashion to the Gapminder example. The test with `px.data.gapminder()` runs splendid. However, when I try to transfer the principle on similarly shaped Excel file of own data, the titled error appears. Here the code:

```
import plotly_express as px
import pandas as pd
import matplotlib as plt

Heisei = pd.read_excel("日本ダム/NihonGapmindFormTest.xlsx")
print(Heisei)

#display of Japanese characters
plt.rcParams['font.sans-serif'] = ['Kozuka Mincho Pr6N']
plt.rcParams['font.serif'] = ['Kozuka Mincho Pr6N']

px.scatter(Heisei, x="Inauguration Year", y="Percent to Dead Volume", animation_frame="Year", animation_group="Dam Name",
           size="Percent to Whole Volume", color="Dam Name", hover_name="Dam Name", 
           #log_y = True, 
           size_max=45, range_x=[1910,2020], range_y=[-100,1000])
```

The table includes no NaNs. Dash.ly seems not to be installed. At least it couldn't be pip uninstalled, as it wasn't found.

This is the complete error warning.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-2fdd1e6f0c53> in <module>()
      2            size="Percent to Whole Volume", color="Dam Name", hover_name="Dam Name",
      3            #log_y = True,
----> 4            size_max=45, range_x=[1910,2020], range_y=[-100,1000])

~\Anaconda3\envs\tensorflow\lib\site-packages\plotly_express\_chart_types.py in scatter(data_frame, x, y, color, symbol, size, hover_name, hover_data, text, facet_row, facet_col, error_x, error_x_minus, error_y, error_y_minus, animation_frame, animation_group, category_orders, labels, color_discrete_sequence, color_discrete_map, color_continuous_scale, color_continuous_midpoint, symbol_sequence, symbol_map, opacity, size_max, marginal_x, marginal_y, trendline, trendline_color_override, log_x, log_y, range_x, range_y, render_mode, title, template, width, height)
     59     In a scatter plot, each row of `data_frame` is represented by a symbol mark in 2D space.
     60     """
---> 61     return make_figure(args=locals(), constructor=go.Scatter)
     62 
     63 

~\Anaconda3\envs\tensorflow\lib\site-packages\plotly_express\_core.py in make_figure(args, constructor, trace_patch, layout_patch)
    653 def make_figure(args, constructor, trace_patch={}, layout_patch={}):
    654     trace_specs, grouped_mappings, sizeref, color_range = infer_config(
--> 655         args, constructor, trace_patch
    656     )
    657     grouper = [x.grouper or one_group for x in grouped_mappings] or [one_group]

~\Anaconda3\envs\tensorflow\lib\site-packages\plotly_express\_core.py in infer_config(args, constructor, trace_patch)
    589     sizeref = 0
    590     if "size" in args and args["size"]:
--> 591         sizeref = args["data_frame"][args["size"]].max() / (
    592             args["size_max"] * args["size_max"]
    593         )

TypeError: 'method' object is not subscriptable
```

As said, I hope this is not redundant. If so, please link me to the respective issue.

Lots of thanks in advance,
Tobias

**Comment by nicolaskruchten** [comment]
Can you post the list of columns in your dataframe? I suspect that `"Percent to Whole Volume"` isn't a valid column name.

I'll work on making clearer error messages for this sort of thing :)

**Comment by tolandwehr** [comment]
@nicolaskruchten Sorry for the late answer. Last days were quite busy.  Here two snippets of Excel and Jupyter display. Hope this is of help.

![JupyterSnippet](https://user-images.githubusercontent.com/41265731/56866198-e658ae00-69d6-11e9-8f4e-9fc398e79dc3.PNG)

![DamTableSnippet](https://user-images.githubusercontent.com/41265731/56866120-13589100-69d6-11e9-87b6-e3a44a84211f.PNG)

**Comment by nicolaskruchten** [comment]
Ah the problem seems to be the line `Heisei = Heisei.dropna` ... you're not actually calling the function and assigning its output: you're assigning the function. That's what when you print it it says "bound method DataFrame.dropna of ..." etc. This means that you're passing a (non-subscriptable) function reference into `px` and not a data frame.

Try replacing that line with `Heisei = Heisei.dropna()` (i.e. add the parentheses :)

**Comment by tolandwehr** [comment]
@nicolaskruchten that did the trick;-)
Thanks for the kind support!

I know, it's not part of the issue, but maybe as a final suggestion: Animation performs quite rugged with 1200 data points, quite less smooth than with the ~200-point Gapminder example. Are there any limitations I've got to consider or are there preferred formats?

**Comment by nicolaskruchten** [comment]
You could try playing with the `render_mode` to see if that affects animation smoothness. IIRC the default is `"svg"` for all animations, and `"webgl"` is the janky one but YMMV.

If you're still having issues, please post some replicable code (i.e. not in a screenshot!) so I can try to help you debug :)
