### ISSUE TITLE
large amounts of data can't be drawn

### ISSUE THREAD

**Issue by CeciliaChiang** [plotly/plotly_express#61]
Hi there,

Hope that this issue is not redundant.  
I'm trying to do univariate analysis with data.
The amount of data is  541909 rows* 8 columns, but the jupyter page can't run. 
I hope that you can fix the problem.

python  3.7.2_2
jupyter notebook  5.7.8
plotly-express       0.1.3

```pyrhon
import plotly_express as px
import pandas as pd

df = pd.read_csv('/Users/jiangqian/data.csv',encoding='ISO-8859-1')
df

px.scatter(df,y="Quantity")
```
![image](https://user-images.githubusercontent.com/50099906/56887105-33a25180-6aa3-11e9-8872-ae705fef44fe.png)

[data.csv.zip](https://github.com/plotly/plotly_express/files/3126846/data.csv.zip)

Thank you : ) .

**Comment by WANGZEQI123** [comment]
Plotly itself said that it's not wise to draw a scatter more than 100000 points or other type more than 10000 points with plotly. For your purpose, you can draw it with matplotlib or seaborn.
By the way, if you do draw the scatter, it's very likely to be a total mess. You'd better make the data into bins to reduce noise. Through this way, you can also reduce the number of point, then you can use plotly to draw the picture and see the relationship.

**Comment by nicolaskruchten** [comment]
So the underlying technology can display up to about a million points, but Jupyter Notebook itself is a bit of a bottleneck in this particular case. Try wrapping your call in a `plotly.graph_objs.FigureWidget()` to see if that helps? 

@jonmmease Figure Widget has a fast path for sending lots of data to the client right? will this happen automatically for Figures in v4?

**Comment by CeciliaChiang** [comment]
> So the underlying technology can display up to about a million points, but Jupyter Notebook itself is a bit of a bottleneck in this particular case. Try wrapping your call in a `plotly.graph_objs.FigureWidget()` to see if that helps?
> 
> @jonmmease Figure Widget has a fast path for sending lots of data to the client right? will this happen automatically for Figures in v4?

Thank you :) 
I got it ~
