### ISSUE TITLE
Is it possible to set the bar color based on the y value?

### ISSUE THREAD

**Issue by WANGZEQI123** [plotly/plotly_express#62]
The current color parameter in plotly_express is more like a group. What I want to do is to produce a bar plot like below, its bar color is proportional to the y value. 
![plot from API (3)](https://user-images.githubusercontent.com/25498045/56943239-2643a080-6b51-11e9-98f1-337df510b800.png)

I wonder if there's a way to do it in plotly express? Or can I modify it use plotly update method?

Thank you so much!

**Comment by nicolaskruchten** [comment]
This isn't possible at the moment but should be an easy addition for the next version :)

**Comment by nicolaskruchten** [comment]
Will be part of the next release, tomorrow!

**Comment by kavyabgowda** [comment]
is it released

**Comment by nicolaskruchten** [comment]
Yes indeed!

**Comment by kavyabgowda** [comment]
Hi,

I have the same requirement where i have to change the colour of bars based
On one more column values which has good, bad values corresponding to
colours  in R shiny.
Please let me know what approaches need to be followed to solve this issue
in R.

Thanks & Regards,
Kavya B

**Comment by nicolaskruchten** [comment]
@kavyabgowda if you're using R then you should check out our R documentation at https://plotly.com/r/ ... this repository is about Plotly Express, which is a Python library :)

**Comment by kavyabgowda** [comment]
Thank you for your response. I will have a look.

Thanks & Best Regards,
Kavya

**Comment by ilyinss** [comment]
can you show code? I need change bar colors based on values
