### ISSUE TITLE
Issue with animation_frame in line plot

### ISSUE THREAD

**Issue by rbuerki** [plotly/plotly_express#64]
I tried to animate a line plot with animation_frame but it did not work. The resulting animation shows no data and the x-axis gets messed up:

![image](https://user-images.githubusercontent.com/44359395/57089254-54b5ad00-6d04-11e9-998e-a5744a757686.png)

Do I do something wrong? 
I use Python 3.7.3.

**Comment by nicolaskruchten** [comment]
If you map both `x` and `animation_frame` to `"time"` you will never see any lines, because you need at least two points per line per frame :)

**Comment by rbuerki** [comment]
Hi Nicolas, thanks - of course. All clear now. I better close this quick ;-). Thank you a lot for the excellent work.
