### ISSUE TITLE
decorated labels based on norm

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly_express#65]
e.g. "percentage of yaxis"

**Comment by xueyanisep** [comment]
fig = px.scatter() 
fig.update(layout=go.Layout(xaxis=dict(tickformat=".2%")))

Hi, you can use this to change the formatting of axis

**Comment by nicolaskruchten** [comment]
Thanks! I had actually just forgotten to close this issue... it was resolved in https://github.com/plotly/plotly_express/commit/9c005fbe69660bbb8b42f9479041cc837e7a0f46 :)

**Comment by nicolaskruchten** [comment]
Ah, I got it: the current `decorated_labels()` function looks at `histfunc` only but not `barnorm` or any other kind of norm :)

**Comment by nicolaskruchten** [comment]
closed in favour of plotly/plotly.py#2986
