### ISSUE TITLE
Pie charts request

### ISSUE THREAD

**Issue by gcamargo1** [plotly/plotly_express#68]
Hello,

Is pie charts in the plans for plotly_express?

thank you

**Comment by nicolaskruchten** [comment]
Just waiting for someone to request it :)

I'll see what I can do!

**Comment by riyadparvez** [comment]
@nicolaskruchten any update on this issue?

**Comment by nicolaskruchten** [comment]
Still in the queue :)

**Comment by nicolaskruchten** [comment]
This is now in `plotly` version 4.4.1: https://community.plot.ly/t/announcing-plotly-py-4-4-1/32514/2
