### ISSUE TITLE
px.histogram: marginal beaks facet_col

### ISSUE THREAD

**Issue by DmitriyG228** [plotly/plotly_express#73]
Adding marginal to px.histogram breaks the facet_col breakdown.

<img width="1336" alt="Screenshot 2019-05-09 at 18 59 49" src="https://user-images.githubusercontent.com/39370484/57468232-c0f85980-728c-11e9-9cfe-e6d71569aef7.png">
<img width="1351" alt="Screenshot 2019-05-09 at 19 00 13" src="https://user-images.githubusercontent.com/39370484/57468239-c2c21d00-728c-11e9-9f59-fa2afb2f1874.png">

**Comment by nicolaskruchten** [comment]
Yes, today faceting and marginals are incompatible and marginals win out... Sometime in the future we'll make it such that you can get both :)

**Comment by nicolaskruchten** [comment]
This now done, you can get marginals on top when using facet_col
