### ISSUE TITLE
Add autosize argument

### ISSUE THREAD

**Issue by theolamayo** [plotly/plotly_express#89]
Hi, thanks for this great library making Plotly faster to use.

I often use the `autosize` option of Plotly layouts, especially when working in Jupyter notebooks. I can use it on Express with `.update(layout=dict(autosize=False))`, however adding it to functions arguments would make it less cumbersome. Would it be reasonable ?

**Comment by nicolaskruchten** [comment]
Hmm. I'm concerned about the expanding set of of kwargs in these functions, so I'll say "not for now"... You can likely do this by creating a plotly.py template and setting it as the default template though do you don't have to keep typing the `update()` call. That can also be made shorter using the new magic-underscores with `.update(layout_autosize=False)` :)

**Comment by theolamayo** [comment]
I understand, I could create a plotly template but I tend to change this setting for each plot. I didn't know about the magic-underscores, thanks!
