### ISSUE TITLE
Plot x-axis is cut off in jupyter lab

### ISSUE THREAD

**Issue by malmaud** [plotly/plotly_express#92]
I'm on the latest jupyter lab (0.35.6) and the latest chrome. When I plot figures, the height is too small to show the x axis by default:

![Screen Shot 2019-05-23 at 4 57 05 PM](https://user-images.githubusercontent.com/987837/58286177-26177900-7d7c-11e9-9aa1-1cd1ef419115.png)

If I double-click the figure to resize it, then its fine:

![Screen Shot 2019-05-23 at 4 56 00 PM](https://user-images.githubusercontent.com/987837/58286223-4810fb80-7d7c-11e9-9be6-b1bc700fefa0.png)

This happens with all plot types, not just bar graphs.

**Comment by jonmmease** [comment]
Hi @malmaud, I think this is probably the same issue as https://github.com/plotly/plotly.py/issues/1572.  

Could you try out the dev build described at https://github.com/plotly/plotly.py/issues/1572#issuecomment-495159557 and see if that helps?

**Comment by malmaud** [comment]
Ya that works, thanks.

**Comment by ned2** [comment]
I've been running into this problem too. Was working around it by manually specifying the height/width. That dev build fixes the problem for me!

**Comment by jonmmease** [comment]
Fixed in https://github.com/plotly/plotly.py/pull/1571 and will be released in plotly.py 3.10.0
