### ISSUE TITLE
hover_data not available

### ISSUE THREAD

**Issue by tmbluth** [plotly/plotly_express#94]
I'm trying to add data that will not be used to change the plot shape but is still valuable for a user (e.g. volumes). Essentially this would be possible in tools like Power BI or Tableau as a "tooltip" where the user hovers over a data point and additional data is provided such as attribute name and values. When checking the GitHub code it looks like the solution is already provided if column(s) is/are provided to the argument `hover_data`. (https://github.com/plotly/plotly_express/blob/master/plotly_express/_chart_types.py). 

The newest version of plotly_express on pip (plotly-express==0.1.3) does not reflect this functionality:

`TypeError: scatter() got an unexpected keyword argument 'hover_data'`
`TypeError: line() got an unexpected keyword argument 'hover_data'`

When providing `hover_data` to common plot types ( px.scatter(), px.line() ) it looks like there is no `hover_data` option. The only alternatives are `hover_name` which highlights the values provided and `text` which displays the values on the plot without hovering. These do not provide the functionality of `hover_data` which I am hoping to access. Is there a mismatch between what's in the source code/documentation and what is on pip?

**Comment by nicolaskruchten** [comment]
The latest version on pip should be 0.2.2 actually...

**Comment by tmbluth** [comment]
It looks like I was blocked from updating due to requirements already being met. However, when manually updating by version number it worked (`pip install plotly_express==0.2.2`)..strange.

After testing version 0.2.2 it works! Sorry for any confusion

**Comment by nicolaskruchten** [comment]
Glad it works!

**Comment by Sandesh-Ghimire** [comment]
its still not working even after installing 0.2.2 any idea how to solve this issues?
TypeError: SelectboxMixin.selectbox() got an unexpected keyword argument 'hover_data'
