### ISSUE TITLE
Overlay Plots

### ISSUE THREAD

**Issue by ingeneious** [plotly/plotly_express#97]
Is there any way to add 2 types of plot (for example line plot/ scatter plot) on top of each other to the same plot?

**Comment by nicolaskruchten** [comment]
There's no Plotly Express argument for this, but you can easily add traces to any plot that comes out of `px` call with `.add_traces()` :)

**Comment by vcmorini** [comment]
Some references:
https://stackoverflow.com/questions/62287001/how-to-overlay-two-plots-in-same-figure-in-plotly
From the docs:
https://plotly.com/python/graphing-multiple-chart-types/

You can also change the layout of the fig and traces: 
https://plotly.com/python/creating-and-updating-figures/

**Comment by nicolaskruchten** [comment]
Closing in favour of: https://github.com/plotly/plotly.py/issues/2648
