### ISSUE TITLE
Add connecting line to scatter plot?

### ISSUE THREAD

**Issue by nextgenusfs** [plotly/plotly_express#99]
Thanks for your work with `plotly_express`, it is generally easy to use.  We've been trying to add a connecting line to a scatter plot and it doesn't seem like there is a setting to do this?  There is the ability to add a `trendline` smoothed over the data, but we were actually just interested in something simpler.  This is possible in `plotly` by specifying the `'mode' = 'lines+markers'`.  We were able to come up with a work around, although seems like providing access to the `mode` in the `scatter` function would be easier.

Work around is:
```
import plotly_express as px
iris = px.data.iris()
p = px.scatter(iris, x="sepal_width", y="sepal_length")
for i in range(0, len(p['data'])):
    p['data'][i]['mode'] = 'lines+markers'
p
```

**Comment by nicolaskruchten** [comment]
So there are a few approaches you can use here... You could use `px.line()` or `px.scatter()` as the basis for your chart, and you could use a few different approached for modifying the `mode` thereafter. (`px.line()` sets `mode='lines'` only by default)

The easiest way to write the code above is:

```python
import plotly_express as px
iris = px.data.iris()
px.scatter(iris, x="sepal_width", y="sepal_length").update_traces(mode="lines+markers")
```

This works for two reasons:

1. `.update_traces()` is a single call that does what your for-loop does, much more tersely
2. it also returns the figure after modifying it, so there's no need to assign it, modify it, then return it

We're working on a comprehensive tutorial for how to effectively and easily modify `px` figures like this :)

**Comment by nicolaskruchten** [comment]
PS: `.update_traces()` also accepts magic-underscores, so if you want to modify nested attributes, you can use e.g. `.update_traces(marker_line_color="black")`

**Comment by nextgenusfs** [comment]
Fantastic, thanks @nicolaskruchten
